export interface AirportSeed {
  iataCode: string;
  name: string;
  city: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
}

// Curated, not a giant scraped global JSON — inherited from adryxflight's
// Nigerian-scheduled-service list, which is still Nigeria-heavy for domestic
// routes. MiniPay's user base spans Celo's other African markets too
// (Kenya, Uganda, Ghana, etc.) — a few more hubs are added below, but this
// is not yet a comprehensive multi-country domestic-airport list. Expand as
// real usage from other markets shows up.
export const AIRPORT_SEEDS: AirportSeed[] = [
  // Nigeria
  {
    iataCode: 'LOS',
    name: 'Murtala Muhammed International Airport',
    city: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.5774,
    longitude: 3.3212,
  },
  {
    iataCode: 'ABV',
    name: 'Nnamdi Azikiwe International Airport',
    city: 'Abuja',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 9.0068,
    longitude: 7.2632,
  },
  {
    iataCode: 'PHC',
    name: 'Port Harcourt International Airport',
    city: 'Port Harcourt',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 5.0155,
    longitude: 6.9496,
  },
  {
    iataCode: 'KAN',
    name: 'Mallam Aminu Kano International Airport',
    city: 'Kano',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 12.0476,
    longitude: 8.5246,
  },
  {
    iataCode: 'ENU',
    name: 'Akanu Ibiam International Airport',
    city: 'Enugu',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.4742,
    longitude: 7.5619,
  },
  {
    iataCode: 'CBQ',
    name: 'Margaret Ekpo International Airport',
    city: 'Calabar',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 4.9757,
    longitude: 8.3477,
  },
  {
    iataCode: 'KAD',
    name: 'Kaduna Airport',
    city: 'Kaduna',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 10.6959,
    longitude: 7.3202,
  },
  {
    iataCode: 'ILR',
    name: 'Ilorin International Airport',
    city: 'Ilorin',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 8.4401,
    longitude: 4.4939,
  },
  {
    iataCode: 'BNI',
    name: 'Benin Airport',
    city: 'Benin City',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.3172,
    longitude: 5.5996,
  },
  {
    iataCode: 'JOS',
    name: 'Yakubu Gowon Airport',
    city: 'Jos',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 9.6398,
    longitude: 8.8695,
  },
  {
    iataCode: 'MIU',
    name: 'Maiduguri International Airport',
    city: 'Maiduguri',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 11.8556,
    longitude: 13.0809,
  },
  {
    iataCode: 'SKO',
    name: 'Sadiq Abubakar III International Airport',
    city: 'Sokoto',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 12.9164,
    longitude: 5.207,
  },
  {
    iataCode: 'QOW',
    name: 'Sam Mbakwe International Cargo Airport',
    city: 'Owerri',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 5.4167,
    longitude: 7.2,
  },
  {
    iataCode: 'YOL',
    name: 'Yola Airport',
    city: 'Yola',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 9.2578,
    longitude: 12.4319,
  },
  {
    iataCode: 'AKR',
    name: 'Akure Airport',
    city: 'Akure',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 7.2467,
    longitude: 5.301,
  },
  {
    iataCode: 'ABB',
    name: 'Asaba International Airport',
    city: 'Asaba',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 6.2035,
    longitude: 6.6649,
  },
  {
    iataCode: 'QUO',
    name: 'Akwa Ibom International Airport',
    city: 'Uyo',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 5.0106,
    longitude: 7.9736,
  },
  {
    iataCode: 'GMO',
    name: 'Gombe Lawanti International Airport',
    city: 'Gombe',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 10.2966,
    longitude: 11.1672,
  },
  {
    iataCode: 'MDI',
    name: 'Makurdi Airport',
    city: 'Makurdi',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 7.7103,
    longitude: 8.5741,
  },
  {
    iataCode: 'BCU',
    name: 'Bauchi State Airport',
    city: 'Bauchi',
    country: 'Nigeria',
    countryCode: 'NG',
    latitude: 10.4834,
    longitude: 9.7534,
  },

  // Other Celo/MiniPay markets
  {
    iataCode: 'NBO',
    name: 'Jomo Kenyatta International Airport',
    city: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    latitude: -1.3192,
    longitude: 36.9278,
  },
  {
    iataCode: 'EBB',
    name: 'Entebbe International Airport',
    city: 'Entebbe',
    country: 'Uganda',
    countryCode: 'UG',
    latitude: 0.0424,
    longitude: 32.4436,
  },
  {
    iataCode: 'DAR',
    name: 'Julius Nyerere International Airport',
    city: 'Dar es Salaam',
    country: 'Tanzania',
    countryCode: 'TZ',
    latitude: -6.8781,
    longitude: 39.2026,
  },
  {
    iataCode: 'KGL',
    name: 'Kigali International Airport',
    city: 'Kigali',
    country: 'Rwanda',
    countryCode: 'RW',
    latitude: -1.9686,
    longitude: 30.1395,
  },

  // International hubs commonly connected through
  {
    iataCode: 'LHR',
    name: 'London Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    latitude: 51.47,
    longitude: -0.4543,
  },
  {
    iataCode: 'DXB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    latitude: 25.2532,
    longitude: 55.3657,
  },
  {
    iataCode: 'AMS',
    name: 'Amsterdam Airport Schiphol',
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    latitude: 52.3105,
    longitude: 4.7683,
  },
  {
    iataCode: 'CDG',
    name: 'Paris Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    latitude: 49.0097,
    longitude: 2.5479,
  },
  {
    iataCode: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    latitude: 41.2753,
    longitude: 28.7519,
  },
  {
    iataCode: 'ADD',
    name: 'Addis Ababa Bole International Airport',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    latitude: 8.9779,
    longitude: 38.7993,
  },
  {
    iataCode: 'JNB',
    name: 'O.R. Tambo International Airport',
    city: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    latitude: -26.1392,
    longitude: 28.246,
  },
  {
    iataCode: 'ACC',
    name: 'Kotoka International Airport',
    city: 'Accra',
    country: 'Ghana',
    countryCode: 'GH',
    latitude: 5.6052,
    longitude: -0.1668,
  },
  {
    iataCode: 'DKR',
    name: 'Blaise Diagne International Airport',
    city: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    latitude: 14.6704,
    longitude: -17.0733,
  },
  {
    iataCode: 'ATL',
    name: 'Hartsfield–Jackson Atlanta International Airport',
    city: 'Atlanta',
    country: 'United States',
    countryCode: 'US',
    latitude: 33.6407,
    longitude: -84.4277,
  },
  {
    iataCode: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'United States',
    countryCode: 'US',
    latitude: 40.6413,
    longitude: -73.7781,
  },
  {
    iataCode: 'DOH',
    name: 'Hamad International Airport',
    city: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    latitude: 25.2731,
    longitude: 51.6081,
  },
  {
    iataCode: 'CAI',
    name: 'Cairo International Airport',
    city: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    latitude: 30.1219,
    longitude: 31.4056,
  },
];
